Update
- 更新 Rust 镜像

diff --git a/shadowsocks-rust/Dockerfile b/shadowsocks-rust/Dockerfile
--- a/shadowsocks-rust/Dockerfile
+++ b/shadowsocks-rust/Dockerfile
@@ -1,34 +1,38 @@
-FROM --platform=$BUILDPLATFORM rust:1.61.0-alpine AS build
+FROM rust:1.61.0-alpine AS builder
 
-ARG TARGETARCH
+LABEL maintainer="WavE Docker Maintainers <waveworkshop@outlook.com>"
+
+ENV COMMIT_ID="5916909ebd44d449d46165dcb95f4259c8c73084"
 
 RUN set -x \
     && apk add --no-cache build-base git 
 
-WORKDIR /root/
-
-RUN cd /root/ \
+RUN mkdir /src \
+    && cd /src \
     && git clone https://github.com/shadowsocks/shadowsocks-rust.git \
-    && case "$TARGETARCH" in \
-    "386") \
-        RUST_TARGET="i686-unknown-linux-musl" \
-        MUSL="i686-linux-musl" \
+    && apkArch="$(apk --print-arch)" \
+    && case "$apkArch" in \
+        "x86") \
+            RUST_TARGET="i686-unknown-linux-musl" \
+            MUSL="i686-linux-musl" \
         ;; \
-    "amd64") \
-        RUST_TARGET="x86_64-unknown-linux-musl" \
-        MUSL="x86_64-linux-musl" \
+        "x86_64") \
+            RUST_TARGET="x86_64-unknown-linux-musl" \
+            MUSL="x86_64-linux-musl" \
         ;; \
-    "arm64") \
-        RUST_TARGET="aarch64-unknown-linux-musl" \
-        MUSL="aarch64-linux-musl" \
+        "aarch64") \
+            RUST_TARGET="aarch64-unknown-linux-musl" \
+            MUSL="aarch64-linux-musl" \
         ;; \
-    *) \
-        echo "Doesn't support $TARGETARCH architecture" \
-        exit 1 \
+        *) \
+            echo "ERROR: Doesn't support $apkArch architecture!" \
+            exit 1 \
         ;; \
     esac \
-    && wget -qO- "https://musl.cc/$MUSL-cross.tgz" | tar -xzC /root/ \
-    && CC=/root/$MUSL-cross/bin/$MUSL-gcc \
+    && wget -qO- "https://musl.cc/$MUSL-cross.tgz" | tar -xzC /src/ \
+    && CC=/src/$MUSL-cross/bin/$MUSL-gcc \
+    && cd shadowsocks-rust \
+    && git reset --hard ${COMMIT_ID} \
     && rustup target add $RUST_TARGET \
     && RUSTFLAGS="-C linker=$CC" \
     && CC=$CC \
@@ -37,12 +41,12 @@ RUN cd /root/ \
 
 FROM alpine:3.16 AS ssserver
 
-COPY --from=build /root/shadowsocks-rust/target/release/sslocal /usr/bin
-COPY --from=build /root/shadowsocks-rust/target/release/ssserver /usr/bin
-COPY --from=build /root/shadowsocks-rust/examples/config.json /etc/shadowsocks-rust/
+COPY --from=builder /src/shadowsocks-rust/target/release/sslocal /usr/local/bin/
+COPY --from=builder /src/shadowsocks-rust/target/release/ssserver /usr/local/bin/
+COPY --from=builder /src/shadowsocks-rust/examples/config.json /etc/shadowsocks-rust/
 
 COPY docker-entrypoint.sh /usr/local/bin/
 
 ENTRYPOINT ["docker-entrypoint.sh"]
 
-CMD ["ssserver"]
+CMD ["ssserver", "--log-without-time", "-a", "nobody", "-c", "/etc/shadowsocks-rust/config.json"]
